name: Daily Release

on:
  schedule:
    # Runs daily at 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set release tag
        id: tag
        run: echo "tag=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      
      - name: Download zip file
        run: |
          # Replace with your actual URL
          curl -L -o release.zip "https://$u:$p@download.maxmind.com/geoip/databases/GeoLite2-Country-CSV/download?suffix=zip"
        env:
          # If authentication is needed, add token/credentials to secrets
          # AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
          u: ${{ secrets.maxminduser }}
          p: ${{ secrets.maxmindpass }}
      
      - name: Verify download
        run: |
          if [ ! -f release.zip ]; then
            echo "Error: release.zip not found"
            exit 1
          fi
          echo "File size: $(du -h release.zip | cut -f1)"
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          name: Release ${{ steps.tag.outputs.tag }}
          body: |
            Automated daily release for ${{ steps.tag.outputs.tag }}
          files: release.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
